FROM golang:latest

# Install any dependencies or tools you need
# RUN apt-get update && apt-get install -y <your-dependencies>

# Set any environment variables
# ENV <VARIABLE_NAME>=<value>

# Switch to the workspace directory
WORKDIR /workspace

# Any other setup you want
